### PR TITLE
Users don't expect worker jobs to idle out.

### PR DESCRIPTION
**Pull request by btovar**
This commit makes it so that the idle timeout is one day.

### CODE REVIEW

**Comment by khurtado** [comment]
I'm fine with this for our current scenario, but I'm a bit nervous about having 24 hours by default on `EC2` resources for example. We especially don't want to have glideins running for a whole day without any actual work being done on resources users are paying per hour.

I think CMS/OSG glideins default to 10 mins in this parameter, but the gwms factory doesn't submit glideins until the frontend matches a job from the submit node. In VC3, we start submitting the glideins before the user submits any work into the submit host, so 5 mins might be too short in that case, but maybe an hour would be better a better start. What do you think?

**Comment by LincolnBryant** [comment]
Note that we do have a --lingertime option. Could we make the default a more modest timeout? Say.. 2 hours? And then pass --lingertime on the commandline if we want longer?

**Comment by btovar** [comment]
Sounds good to me.

**Comment by LincolnBryant** [comment]
Decided on 2 hours as a more reasonable timeframe. We can still use `--lingertime=86400` within the infrastructure if we like. I expect this default will change again eventually.

**Pull request merged**
